objects/Feature__c.object
<CustomObject>
    <fields>
        <fullName>Genre__c</fullName>
        <label>Genre</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Drama</fullName>
                </value>
                <value>
                    <fullName>Epic</fullName>
                </value>
                <value>
                    <fullName>Comedy</fullName>
                </value>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Animation</fullName>
                </value>
                <value>
                    <fullName>Musical</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Release_Date__c</fullName>
        <label>Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trailer_Impression__c</fullName>
        <label>Trailer Impression1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Showing__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Feature__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Feature</label>
        <referenceTo>Feature__c</referenceTo>
        <relationshipLabel>Showings</relationshipLabel>
        <relationshipName>ShowingFeature</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Screen_Number__c</fullName>
        <label>Screen Number</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tickets_Sold__c</fullName>
        <label>Tickets Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Showing</label>
    <nameField>
        <label>Showing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Trailer__c.object
<CustomObject>
    <fields>
        <fullName>Feature__c</fullName>
        <label>Feature</label>
        <referenceTo>Feature__c</referenceTo>
        <relationshipLabel>Trailers</relationshipLabel>
        <relationshipName>Trailers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Showing__c</fullName>
        <label>Showing</label>
        <referenceTo>Showing__c</referenceTo>
        <relationshipLabel>Trailers</relationshipLabel>
        <relationshipName>Trailers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trailer</label>
    <nameField>
        <label>Trailer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TrailerTriggerHandlerTest.cls
@isTest
public class TrailerTriggerHandlerTest {
    private static testMethod void trlrtest(){
        List<Feature__c> ftrList=new List<Feature__c>();  //Creating the list of feature
        List<Showing__c> shwList=new List<Showing__c>();  //Creating the List of showing
        List<Trailer__c> trlList=new List<Trailer__c>();  //Creating the List of Trailer
        Integer i=0;
        for(i=0;i<3;i++){
            Feature__c testftr=new Feature__c(name='testfeature'+String.valueOf(i),Genre__c='Action',Release_Date__c=System.today(),Trailer_Impression__c=123);
            if(i/2==0){  
                testftr.Genre__c='Animation';
            }else{
                testftr.Genre__c='Comedy';
            }
            ftrList.add(testftr);           
        }
        insert ftrList;
        for(i=0;i<3;i++){
           Showing__c shw=new showing__c(name='testfeature'+String.valueOf(i),Date__c=System.today(),Screen_Number__c='test',Start_Time__c='test',Tickets_Sold__c=10); 
           
            shw.Feature__c=ftrList.get(i).ID;
            shwList.add(shw);
        }
        insert shwList; 
        for(i=0;i<3;i++){
        Trailer__c trl=new Trailer__c(name='testfeature'+String.valueOf(i),Feature__c=ftrList.get(i).ID,Showing__c=shwList.get(i).ID);
            trlList.add(trl);
            }
        Test.startTest();
        insert trlList;
        Test.stopTest();
        //Trailer__c testTrlr=new Trailer__c(name='TestTrailer')
        
    }
}