objects/Feature__c.object
<CustomObject>
    <fields>
        <fullName>Trailer_Impression__c</fullName>
        <label>Trailer Impression1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Showing__c.object
<CustomObject>
    <fields>
        <fullName>Feature__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Feature</label>
        <referenceTo>Feature__c</referenceTo>
        <relationshipLabel>Showings</relationshipLabel>
        <relationshipName>ShowingFeature</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tickets_Sold__c</fullName>
        <label>Tickets Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Showing</label>
    <nameField>
        <label>Showing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ShowingTriggerHandler.cls
/*
Trigger handler on the Showing object.
*/
public class ShowingTriggerHandler {
    public static void onAfterUpdate(List<Showing__c> shwList,Map<Id,Showing__c> shwMap){
        ticketSold(shwList,shwMap);
    }
    public static void onAfterInsert(Map<Id,Showing__c> shwMap){
        ticketSold(shwMap.Values(),null);
    }
    //Code to check the count of the ticket solds 
    private static void ticketSold(List<Showing__c> shwList,Map<Id,Showing__c> shwMap){
        Map<ID,Decimal> ftrTckt=new Map<ID,Decimal>();
        Decimal tktsold;
        List<Feature__C> ftrList=new List<Feature__C>();
        Set<Id> ftrIDs=new Set<Id>();
        //Calculating the ticket sold on the feature
        for(Showing__c show : shwList){
            ftrIDs.add(show.Feature__c);
        }
        for(Showing__c show : [Select Id,Tickets_Sold__c,Feature__c FROM Showing__c Where Feature__c in : ftrIDs]){
            if(ftrTckt.containsKey(show.Feature__c)){
                tktsold=ftrTckt.get(show.Feature__c)+show.Tickets_Sold__c ;
                ftrTckt.put(show.feature__c,tktsold);
            }else if(show.feature__c!=null){
                ftrTckt.put(show.feature__c,show.Tickets_Sold__c);
            }    
        }
        System.debug('---->'+ftrTckt);
        //Setting the trailer impression for the feature
        if(ftrTckt!=null){
            for(Feature__c ft : [SELECT ID ,Trailer_Impression__c FROM Feature__c Where Id in : ftrTckt.keySet()]){
                if(ftrTckt.containsKey(ft.Id)){
                    ft.Trailer_Impression__c=ftrTckt.get(ft.Id);
                }
                ftrList.add(ft);
            }
            if(ftrList!=null){
                update ftrList;
                System.debug('----->ftrTckt='+ftrTckt);
            }
        }    
    }
}